# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/subworkflows/yaml-schema.json
name: "{{ component_name_underscore }}"
description: {{ description }}
keywords:
    {{ keywords }}
components:
    {{ components }}

{{ inputs_yml_swf }}

{{ outputs_yml_swf }}

authors:
    - "{{ author }}"
maintainers:
    - "{{ author }}"
