# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "{{ component_name_underscore }}"
description: {{ description }}
keywords:
  {{ keywords }}
tools:
  - "{{ component }}":
      description: "{{ tool_description }}"
      homepage: "{{ tool_doc_url }}"
      documentation: "{{ tool_doc_url }}"
      tool_dev_url: "{{ tool_dev_url }}"
      doi: ""
      licence: {{ tool_licence }}
      identifier: {{ tool_identifier }}

{{ inputs_yml_str }}

{{ outputs_yml_str }}

authors:
  - "{{ author }}"
maintainers:
  - "{{ author }}"
